config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/#{I18n.locale}"), as: :redirected_root
  scope "(:locale)", locale: /uk|en/ do
    root to: "couriers#index"
    resources :couriers, except: [:delete] do
      resources :packages, only: [:create, :update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
  has_many :packages

  validates_presence_of :name, :email
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier
  validates :tracking_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :set_courier, only: [:show, :edit, :update]

  def index
    @couriers = Courier.order(:id)
  end

  def show
  end

  def new
    @courier = Courier.new
  end

  def edit
  end

  def create
    @courier = Courier.new(courier_params)
    respond_to do |format|
      if @courier.save
        format.html { redirect_to @courier, notice: t('courier_added') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @courier.update(courier_params)
        format.html { redirect_to @courier, notice: t('courier_edited') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_courier
    @courier = Courier.find(params[:id])
  end

  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_courier, only: [:create, :update]

  def create
    @package = @courier.packages.create(package_params)
    respond_to do |format|
      if @package.save
        format.html { redirect_to courier_path(@courier), notice: t('package_added') }
      else
        format.html { render :'couriers/show', status: :unprocessable_entity }
      end
    end
  end

  def update
    @package = Package.find(params[:id])
    @package.update(delivery_status: true)
    redirect_to courier_path(@courier), notice: t('package_delivered')
  end

  private
  def set_courier
    @courier = Courier.find(params[:courier_id])
  end

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courier_helper.rb
module CourierHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/_form.html.erb
<%= form_with(model: courier, local: true) do |form| %>
  <% if @courier.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('activerecord.errors.errors_title') %></h2>

      <ul>
        <% @courier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :name, class: "form-label mt-3" %>
    <%= form.text_field :name, class: "form-control" %>

    <%= form.label :email, class: "form-label mt-3" %>
    <%= form.email_field :email, class: "form-control" %>

    <%= form.submit class: "btn btn-primary px-4 mt-3" %>
<% end %>

app/views/couriers/edit.html.erb
<h1><%= t('edit') %></h1>
<%= render 'form', courier: @courier %>

app/views/couriers/index.html.erb
<main>
  <div class="row g-5">
    <div class="col-12">
      <h1><%= t('all_couriers') %></h1>
      <ul class="icon-list">
        <% @couriers.each do |courier| %>
          <li>
            <%= courier.name %>,
            <%= courier.email %>,
            <% if courier.packages.count == 0 %>
              <%= t('no_packages') %>
            <% elsif courier.packages.count < 5 %>
              <%= courier.packages.count.to_s + " " + t('packages4-') %>
            <% elsif courier.packages.count > 4 %>
              <%= courier.packages.count.to_s + " " + t('packages5+') %>
            <% end %>
            - <%= link_to t('show'), courier %>, <%= link_to t('edit'), edit_courier_path(courier) %>
          </li>
        <% end %>
      </ul>
      <%= link_to t('add_new_courier'), new_courier_path, class: "btn btn-primary px-4" %>
    </div>
  </div>
</main>

app/views/couriers/new.html.erb
<h1><%= t('add_new_courier') %></h1>
<%= render 'form', courier: @courier %>

app/views/couriers/show.html.erb
<h1><%= t('courier') %>: <%= @courier.name %></h1>
<h4><%= t('email') %>: <%= mail_to(@courier.email) %></h4>

<div>
  <%= link_to t('edit'), edit_courier_path(@courier) %>
  <%= link_to t('to_couriers_list'), couriers_path %>
</div>

<h2 class="mt-3"><%= t('packages4-').capitalize %></h2>
<% if @courier.packages.count > 0 %>
  <% @courier.packages.order(:id).each do |package| %>
    <p>
      <%= package.tracking_number %>,
      <%= package.delivery_status == true ? t('delivered') : t('not_delivered') %>
      <% if package.delivery_status == false %>
        <%= link_to t('mark_as_delivered'), courier_package_path(@courier, package), method: :patch, data: { confirm: t('delivered?') } %></p>
    <% end %>
  <% end %>
  <% else %>
    <%= t('no_packages') %>
<% end %>

<h2 class="mt-3"><%= t('add_new_package') %></h2>
<%= render "packages/form", courier: @courier, package: @courier.packages.build %>

app/views/layouts/_header.html.erb
<header>
  <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <%= link_to "DeliveryApp", root_path, class: "d-flex align-items-center text-dark text-decoration-none fs-4" %>


    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <%= link_to t('to_couriers_list'), couriers_path, class: "me-3 py-2 text-dark text-decoration-none" %>
      <% if I18n.locale == :uk %>
        <%= link_to "In English", { :locale => 'en' }, class: "me-3 py-2 text-dark text-decoration-none" %>
      <% else %>
        <%= link_to "Українською", { :locale => 'uk' }, class: "me-3 py-2 text-dark text-decoration-none" %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_notifications.html.erb
<div class="alert-success text-center" id="notice"><%= notice %></div>
<div class="alert-danger text-center" id="alert"><%= alert %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <div class="col-lg-8 mx-auto p-3 py-md-5">
      <%= render 'layouts/header' %>
      <%= render 'layouts/notifications' %>
      <%= yield %>
    </div>
  </body>
</html>